// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Page
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * Meta Title field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: My title for Search Engine
     * - **API ID Path**: page.meta_title
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_title: prismicT.KeyTextField;
    /**
     * Meta Description field in *Page*
     *
     * - **Field Type**: Text
     * - **Placeholder**: The description that will appear in search engine
     * - **API ID Path**: page.meta_description
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    meta_description: prismicT.KeyTextField;
    /**
     * Social Cards - Facebook & Twitter field in *Page*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: page.social_cards[]
     * - **Tab**: SEO Metadata
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    social_cards: prismicT.GroupField<Simplify<PageDocumentDataSocialCardsItem>>;
}
/**
 * Primary content in Page → Slice Zone → `alternate_grid` → Primary
 *
 */
interface PageDocumentDataSlicesAlternateGridSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `alternate_grid` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * title field in *Page → Slice Zone → `alternate_grid` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *Page → Slice Zone → `alternate_grid` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Optional image field in *Page → Slice Zone → `alternate_grid` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.primary.optional_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    optional_image: prismicT.ImageField<never>;
    /**
     * Image side field in *Page → Slice Zone → `alternate_grid` → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **Default Value**: left
     * - **API ID Path**: page.slices[].alternate_grid.primary.image_side
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    image_side: prismicT.SelectField<"left" | "right", "filled">;
}
/**
 * Item in Page → Slice Zone → `alternate_grid` → Items
 *
 */
export interface PageDocumentDataSlicesAlternateGridSliceItem {
    /**
     * Optional Icon field in *Page → Slice Zone → `alternate_grid` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.items[].optional_icon
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    optional_icon: prismicT.ImageField<never>;
    /**
     * title field in *Page → Slice Zone → `alternate_grid` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *Page → Slice Zone → `alternate_grid` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].alternate_grid.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
export type PageDocumentDataSlicesAlternateGridSlice = prismicT.Slice<"alternate_grid", Simplify<PageDocumentDataSlicesAlternateGridSlicePrimary>, Simplify<PageDocumentDataSlicesAlternateGridSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `call_to_action` → Primary
 *
 */
interface PageDocumentDataSlicesCallToActionSlicePrimary {
    /**
     * Icon Image field in *Page → Slice Zone → `call_to_action` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].call_to_action.primary.icon_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    icon_image: prismicT.ImageField<never>;
    /**
     * Title field in *Page → Slice Zone → `call_to_action` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].call_to_action.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Paragraph field in *Page → Slice Zone → `call_to_action` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].call_to_action.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * Button Link field in *Page → Slice Zone → `call_to_action` → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].call_to_action.primary.button_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    button_link: prismicT.LinkField;
    /**
     * Button Label field in *Page → Slice Zone → `call_to_action` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Text for button
     * - **API ID Path**: page.slices[].call_to_action.primary.button_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    button_label: prismicT.KeyTextField;
}
export type PageDocumentDataSlicesCallToActionSlice = prismicT.Slice<"call_to_action", Simplify<PageDocumentDataSlicesCallToActionSlicePrimary>, never>;
/**
 * Primary content in Page → Slice Zone → `cards_carousel` → Primary
 *
 */
interface PageDocumentDataSlicesCardsCarouselSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `cards_carousel` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `cards_carousel` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `cards_carousel` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Page → Slice Zone → `cards_carousel` → Items
 *
 */
export interface PageDocumentDataSlicesCardsCarouselSliceItem {
    /**
     * Image field in *Page → Slice Zone → `cards_carousel` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Title field in *Page → Slice Zone → `cards_carousel` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Content field in *Page → Slice Zone → `cards_carousel` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].cards_carousel.items[].content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
    /**
     * Additional Info field in *Page → Slice Zone → `cards_carousel` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: eg. name of person in testimonial
     * - **API ID Path**: page.slices[].cards_carousel.items[].additional_info
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    additional_info: prismicT.RichTextField;
}
export type PageDocumentDataSlicesCardsCarouselSlice = prismicT.Slice<"cards_carousel", Simplify<PageDocumentDataSlicesCardsCarouselSlicePrimary>, Simplify<PageDocumentDataSlicesCardsCarouselSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `customer_logos` → Primary
 *
 */
interface PageDocumentDataSlicesCustomerLogosSlicePrimary {
    /**
     * Eyebrow Headline field in *Page → Slice Zone → `customer_logos` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Trusted by
     * - **API ID Path**: page.slices[].customer_logos.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.TitleField;
    /**
     * Call To Action field in *Page → Slice Zone → `customer_logos` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: View customer stories
     * - **API ID Path**: page.slices[].customer_logos.primary.call_to_action
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    call_to_action: prismicT.RichTextField;
    /**
     * Call to Action Link field in *Page → Slice Zone → `customer_logos` → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Could be a signup link, or a link to customer stories
     * - **API ID Path**: page.slices[].customer_logos.primary.call_to_action_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    call_to_action_link: prismicT.LinkField;
}
/**
 * Item in Page → Slice Zone → `customer_logos` → Items
 *
 */
export interface PageDocumentDataSlicesCustomerLogosSliceItem {
    /**
     * Logo field in *Page → Slice Zone → `customer_logos` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].customer_logos.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * link field in *Page → Slice Zone → `customer_logos` → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Could be a link to use case, press article, signup...
     * - **API ID Path**: page.slices[].customer_logos.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
export type PageDocumentDataSlicesCustomerLogosSlice = prismicT.Slice<"customer_logos", Simplify<PageDocumentDataSlicesCustomerLogosSlicePrimary>, Simplify<PageDocumentDataSlicesCustomerLogosSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `faq_section` → Primary
 *
 */
interface PageDocumentDataSlicesFaqSectionSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `faq_section` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Reinforce your copy with a key-worded text, to be displayed before title
     * - **API ID Path**: page.slices[].faq_section.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * title field in *Page → Slice Zone → `faq_section` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Title
     * - **API ID Path**: page.slices[].faq_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `faq_section` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].faq_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Optional image field in *Page → Slice Zone → `faq_section` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].faq_section.primary.optional_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    optional_image: prismicT.ImageField<never>;
}
/**
 * Item in Page → Slice Zone → `faq_section` → Items
 *
 */
export interface PageDocumentDataSlicesFaqSectionSliceItem {
    /**
     * Title field in *Page → Slice Zone → `faq_section` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Which browsers do you support?
     * - **API ID Path**: page.slices[].faq_section.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Text field in *Page → Slice Zone → `faq_section` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: The answer to the question
     * - **API ID Path**: page.slices[].faq_section.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
export type PageDocumentDataSlicesFaqSectionSlice = prismicT.Slice<"faq_section", Simplify<PageDocumentDataSlicesFaqSectionSlicePrimary>, Simplify<PageDocumentDataSlicesFaqSectionSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `feature_testimonials` → Primary
 *
 */
interface PageDocumentDataSlicesFeatureTestimonialsSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `feature_testimonials` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Reinforce your copy with a key-worded text, to be displayed before title
     * - **API ID Path**: page.slices[].feature_testimonials.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `feature_testimonials` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Our testimonial
     * - **API ID Path**: page.slices[].feature_testimonials.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `feature_testimonials` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: These are some awesome tutorials from our awesome clients ...
     * - **API ID Path**: page.slices[].feature_testimonials.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Feature Illustration field in *Page → Slice Zone → `feature_testimonials` → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].feature_testimonials.primary.feature_illustration
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    feature_illustration: prismicT.ImageField<never>;
}
/**
 * Item in Page → Slice Zone → `feature_testimonials` → Items
 *
 */
export interface PageDocumentDataSlicesFeatureTestimonialsSliceItem {
    /**
     * Client logo field in *Page → Slice Zone → `feature_testimonials` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].feature_testimonials.items[].client_logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    client_logo: prismicT.ImageField<never>;
    /**
     * Profile Pic field in *Page → Slice Zone → `feature_testimonials` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].feature_testimonials.items[].profile_pic
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_pic: prismicT.ImageField<never>;
    /**
     * Quote field in *Page → Slice Zone → `feature_testimonials` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Lorem ipsum dolor sit amet, ....
     * - **API ID Path**: page.slices[].feature_testimonials.items[].quote
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote: prismicT.RichTextField;
    /**
     * Name field in *Page → Slice Zone → `feature_testimonials` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: John McJohn
     * - **API ID Path**: page.slices[].feature_testimonials.items[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.RichTextField;
    /**
     * Role position field in *Page → Slice Zone → `feature_testimonials` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Creative Director
     * - **API ID Path**: page.slices[].feature_testimonials.items[].role_position
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    role_position: prismicT.RichTextField;
}
export type PageDocumentDataSlicesFeatureTestimonialsSlice = prismicT.Slice<"feature_testimonials", Simplify<PageDocumentDataSlicesFeatureTestimonialsSlicePrimary>, Simplify<PageDocumentDataSlicesFeatureTestimonialsSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `images_slider` → Primary
 *
 */
interface PageDocumentDataSlicesImagesSliderSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `images_slider` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].images_slider.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `images_slider` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].images_slider.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `images_slider` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].images_slider.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Page → Slice Zone → `images_slider` → Items
 *
 */
export interface PageDocumentDataSlicesImagesSliderSliceItem {
    /**
     * Full Width Image field in *Page → Slice Zone → `images_slider` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].images_slider.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Description field in *Page → Slice Zone → `images_slider` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].images_slider.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
export type PageDocumentDataSlicesImagesSliderSlice = prismicT.Slice<"images_slider", Simplify<PageDocumentDataSlicesImagesSliderSlicePrimary>, Simplify<PageDocumentDataSlicesImagesSliderSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `pricing_table` → Primary
 *
 */
interface PageDocumentDataSlicesPricingTableSlicePrimary {
    /**
     * Eyebrow Headline field in *Page → Slice Zone → `pricing_table` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Pricing plans
     * - **API ID Path**: page.slices[].pricing_table.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `pricing_table` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Choose the plan
     * - **API ID Path**: page.slices[].pricing_table.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `pricing_table` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Choose the version that works for you ...
     * - **API ID Path**: page.slices[].pricing_table.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Page → Slice Zone → `pricing_table` → Items
 *
 */
export interface PageDocumentDataSlicesPricingTableSliceItem {
    /**
     * Plan title field in *Page → Slice Zone → `pricing_table` → Items*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Simple, Gold, Premium...
     * - **API ID Path**: page.slices[].pricing_table.items[].plan_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    plan_title: prismicT.TitleField;
    /**
     * Price Option field in *Page → Slice Zone → `pricing_table` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Free, $19, Contact us...
     * - **API ID Path**: page.slices[].pricing_table.items[].price_option
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    price_option: prismicT.RichTextField;
    /**
     * Features field in *Page → Slice Zone → `pricing_table` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A list of features using bullet list
     * - **API ID Path**: page.slices[].pricing_table.items[].features
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    features: prismicT.RichTextField;
    /**
     * Call To Action field in *Page → Slice Zone → `pricing_table` → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to Signup / More info...
     * - **API ID Path**: page.slices[].pricing_table.items[].call_to_action
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    call_to_action: prismicT.LinkField;
    /**
     * Call To Action Text field in *Page → Slice Zone → `pricing_table` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Start your free trial
     * - **API ID Path**: page.slices[].pricing_table.items[].call_to_action_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    call_to_action_text: prismicT.RichTextField;
}
export type PageDocumentDataSlicesPricingTableSlice = prismicT.Slice<"pricing_table", Simplify<PageDocumentDataSlicesPricingTableSlicePrimary>, Simplify<PageDocumentDataSlicesPricingTableSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `testimonials_slider` → Primary
 *
 */
interface PageDocumentDataSlicesTestimonialsSliderSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `testimonials_slider` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `testimonials_slider` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Paragraph field in *Page → Slice Zone → `testimonials_slider` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.primary.paragraph
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    paragraph: prismicT.RichTextField;
    /**
     * Button Link field in *Page → Slice Zone → `testimonials_slider` → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.primary.button_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    button_link: prismicT.LinkField;
    /**
     * Button Label field in *Page → Slice Zone → `testimonials_slider` → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Text for button
     * - **API ID Path**: page.slices[].testimonials_slider.primary.button_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    button_label: prismicT.KeyTextField;
}
/**
 * Item in Page → Slice Zone → `testimonials_slider` → Items
 *
 */
export interface PageDocumentDataSlicesTestimonialsSliderSliceItem {
    /**
     * image field in *Page → Slice Zone → `testimonials_slider` → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * testimonial field in *Page → Slice Zone → `testimonials_slider` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].testimonials_slider.items[].testimonial
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    testimonial: prismicT.RichTextField;
    /**
     * person field in *Page → Slice Zone → `testimonials_slider` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Their full name
     * - **API ID Path**: page.slices[].testimonials_slider.items[].person
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    person: prismicT.KeyTextField;
    /**
     * title field in *Page → Slice Zone → `testimonials_slider` → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Their title
     * - **API ID Path**: page.slices[].testimonials_slider.items[].title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
export type PageDocumentDataSlicesTestimonialsSliderSlice = prismicT.Slice<"testimonials_slider", Simplify<PageDocumentDataSlicesTestimonialsSliderSlicePrimary>, Simplify<PageDocumentDataSlicesTestimonialsSliderSliceItem>>;
/**
 * Primary content in Page → Slice Zone → `video_highlights` → Primary
 *
 */
interface PageDocumentDataSlicesVideoHighlightsSlicePrimary {
    /**
     * Eyebrow headline field in *Page → Slice Zone → `video_highlights` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Reinforce your copy with a key-worded text, to be displayed before title
     * - **API ID Path**: page.slices[].video_highlights.primary.eyebrow_headline
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    eyebrow_headline: prismicT.RichTextField;
    /**
     * Title field in *Page → Slice Zone → `video_highlights` → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Video Highlights
     * - **API ID Path**: page.slices[].video_highlights.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Page → Slice Zone → `video_highlights` → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: These are some awesome videos ...
     * - **API ID Path**: page.slices[].video_highlights.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in Page → Slice Zone → `video_highlights` → Items
 *
 */
export interface PageDocumentDataSlicesVideoHighlightsSliceItem {
    /**
     * Video title field in *Page → Slice Zone → `video_highlights` → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: My awesome video
     * - **API ID Path**: page.slices[].video_highlights.items[].video_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    video_title: prismicT.RichTextField;
    /**
     * Video src field in *Page → Slice Zone → `video_highlights` → Items*
     *
     * - **Field Type**: Embed
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[].video_highlights.items[].video_src
     * - **Documentation**: https://prismic.io/docs/core-concepts/embed
     *
     */
    video_src: prismicT.EmbedField;
}
export type PageDocumentDataSlicesVideoHighlightsSlice = prismicT.Slice<"video_highlights", Simplify<PageDocumentDataSlicesVideoHighlightsSlicePrimary>, Simplify<PageDocumentDataSlicesVideoHighlightsSliceItem>>;
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = PageDocumentDataSlicesAlternateGridSlice | PageDocumentDataSlicesCallToActionSlice | PageDocumentDataSlicesCardsCarouselSlice | PageDocumentDataSlicesCustomerLogosSlice | PageDocumentDataSlicesFaqSectionSlice | PageDocumentDataSlicesFeatureTestimonialsSlice | PageDocumentDataSlicesImagesSliderSlice | PageDocumentDataSlicesPricingTableSlice | PageDocumentDataSlicesTestimonialsSliderSlice | PageDocumentDataSlicesVideoHighlightsSlice;
/**
 * Item in Page → Social Cards - Facebook & Twitter
 *
 */
export interface PageDocumentDataSocialCardsItem {
    /**
     * Social Card Image field in *Page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.social_cards[].social_card_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    social_card_image: prismicT.ImageField<never>;
    /**
     * Social Card TItle field in *Page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.social_cards[].social_card_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_title: prismicT.KeyTextField;
    /**
     * Social card description field in *Page → Social Cards - Facebook & Twitter*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.social_cards[].social_card_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    social_card_description: prismicT.KeyTextField;
}
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Service documents */
interface ServiceDocumentData {
    /**
     * Title field in *Service*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Service*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Service*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: service.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * hero_image field in *Service*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: service.hero_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    hero_image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Service*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: service.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ServiceDocumentDataSlicesSlice>;
}
/**
 * Slice for *Service → Slice Zone*
 *
 */
type ServiceDocumentDataSlicesSlice = TextBlockSlice | DrinkDrivingCalculatorSlice | ConveyancingCalculatorSlice | TestimonialsSlice;
/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, "service", Lang>;
export type AllDocumentTypes = PageDocument | ServiceDocument;
/**
 * Default variation for ConveyancingCalculator Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ConveyancingCalculator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ConveyancingCalculatorSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *ConveyancingCalculator*
 *
 */
type ConveyancingCalculatorSliceVariation = ConveyancingCalculatorSliceDefault;
/**
 * ConveyancingCalculator Shared Slice
 *
 * - **API ID**: `conveyancing_calculator`
 * - **Description**: `ConveyancingCalculator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ConveyancingCalculatorSlice = prismicT.SharedSlice<"conveyancing_calculator", ConveyancingCalculatorSliceVariation>;
/**
 * Default variation for DrinkDrivingCalculator Slice
 *
 * - **API ID**: `default`
 * - **Description**: `DrinkDrivingCalculator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DrinkDrivingCalculatorSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *DrinkDrivingCalculator*
 *
 */
type DrinkDrivingCalculatorSliceVariation = DrinkDrivingCalculatorSliceDefault;
/**
 * DrinkDrivingCalculator Shared Slice
 *
 * - **API ID**: `drink_driving_calculator`
 * - **Description**: `DrinkDrivingCalculator`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DrinkDrivingCalculatorSlice = prismicT.SharedSlice<"drink_driving_calculator", DrinkDrivingCalculatorSliceVariation>;
/**
 * Primary content in Testimonials → Primary
 *
 */
interface TestimonialsSliceDefaultPrimary {
    /**
     * Title field in *Testimonials → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: testimonials.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Testimonials → Items
 *
 */
export interface TestimonialsSliceDefaultItem {
    /**
     * quote field in *Testimonials → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].quote
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote: prismicT.RichTextField;
    /**
     * name field in *Testimonials → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].name
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * position field in *Testimonials → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].position
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    position: prismicT.KeyTextField;
    /**
     * rating field in *Testimonials → Items*
     *
     * - **Field Type**: Number
     * - **Placeholder**: *None*
     * - **API ID Path**: testimonials.items[].rating
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    rating: prismicT.NumberField;
}
/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TestimonialsSliceDefaultPrimary>, Simplify<TestimonialsSliceDefaultItem>>;
/**
 * Slice variation for *Testimonials*
 *
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;
/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: `Testimonials`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TestimonialsSlice = prismicT.SharedSlice<"testimonials", TestimonialsSliceVariation>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
    /**
     * content field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: text_block.primary.content
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    content: prismicT.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextBlockSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismicT.SharedSlice<"text_block", TextBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesAlternateGridSlicePrimary, PageDocumentDataSlicesAlternateGridSliceItem, PageDocumentDataSlicesAlternateGridSlice, PageDocumentDataSlicesCallToActionSlicePrimary, PageDocumentDataSlicesCallToActionSlice, PageDocumentDataSlicesCardsCarouselSlicePrimary, PageDocumentDataSlicesCardsCarouselSliceItem, PageDocumentDataSlicesCardsCarouselSlice, PageDocumentDataSlicesCustomerLogosSlicePrimary, PageDocumentDataSlicesCustomerLogosSliceItem, PageDocumentDataSlicesCustomerLogosSlice, PageDocumentDataSlicesFaqSectionSlicePrimary, PageDocumentDataSlicesFaqSectionSliceItem, PageDocumentDataSlicesFaqSectionSlice, PageDocumentDataSlicesFeatureTestimonialsSlicePrimary, PageDocumentDataSlicesFeatureTestimonialsSliceItem, PageDocumentDataSlicesFeatureTestimonialsSlice, PageDocumentDataSlicesImagesSliderSlicePrimary, PageDocumentDataSlicesImagesSliderSliceItem, PageDocumentDataSlicesImagesSliderSlice, PageDocumentDataSlicesPricingTableSlicePrimary, PageDocumentDataSlicesPricingTableSliceItem, PageDocumentDataSlicesPricingTableSlice, PageDocumentDataSlicesTestimonialsSliderSlicePrimary, PageDocumentDataSlicesTestimonialsSliderSliceItem, PageDocumentDataSlicesTestimonialsSliderSlice, PageDocumentDataSlicesVideoHighlightsSlicePrimary, PageDocumentDataSlicesVideoHighlightsSliceItem, PageDocumentDataSlicesVideoHighlightsSlice, PageDocumentDataSlicesSlice, PageDocumentDataSocialCardsItem, PageDocument, ServiceDocumentData, ServiceDocumentDataSlicesSlice, ServiceDocument, AllDocumentTypes, ConveyancingCalculatorSliceDefault, ConveyancingCalculatorSliceVariation, ConveyancingCalculatorSlice, DrinkDrivingCalculatorSliceDefault, DrinkDrivingCalculatorSliceVariation, DrinkDrivingCalculatorSlice, TestimonialsSliceDefaultPrimary, TestimonialsSliceDefaultItem, TestimonialsSliceDefault, TestimonialsSliceVariation, TestimonialsSlice, TextBlockSliceDefaultPrimary, TextBlockSliceDefault, TextBlockSliceVariation, TextBlockSlice };
    }
}
