// Code generated by Slice Machine. DO NOT EDIT.

import DrinkDrivingCalculator from './DrinkDrivingCalculator';
import TextBlock from './TextBlock';

export {
	DrinkDrivingCalculator,
	TextBlock,
};

export const components = {
	drink_driving_calculator: DrinkDrivingCalculator,
	text_block: TextBlock,
};
